[package]
name = "site"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["serde_derive"] }
wasm-bindgen = "0.2.100"
web-sys = "0.3.77"
yew = { version = "0.21.0", features = ["csr"] }
